-- Replace placeholder skill entries with real OpenClaw bundled skills.
-- Delete old fake entries (cascade removes machine_capabilities referencing them).
DELETE FROM machine_capabilities WHERE entry_id IN ('web-search', 'code-runner', 'file-manager', 'image-gen');
DELETE FROM registry_entries WHERE id IN ('web-search', 'code-runner', 'file-manager', 'image-gen');

-- Seed real bundled skills from the OpenClaw gateway source.
-- config_template uses skills.entries.<id>.enabled = true format.
INSERT INTO registry_entries (id, type, name, description, config_template, sort_order)
VALUES
    ('1password', 'skill', '1Password', 'Set up and use 1Password CLI (op) for secrets management',
     '{"skills":{"entries":{"1password":{"enabled":true}}}}'::jsonb, 1),
    ('apple-notes', 'skill', 'Apple Notes', 'Manage Apple Notes via the memo CLI on macOS',
     '{"skills":{"entries":{"apple-notes":{"enabled":true}}}}'::jsonb, 2),
    ('apple-reminders', 'skill', 'Apple Reminders', 'Manage Apple Reminders via remindctl CLI',
     '{"skills":{"entries":{"apple-reminders":{"enabled":true}}}}'::jsonb, 3),
    ('bear-notes', 'skill', 'Bear Notes', 'Create, search, and manage Bear notes via grizzly CLI',
     '{"skills":{"entries":{"bear-notes":{"enabled":true}}}}'::jsonb, 4),
    ('camsnap', 'skill', 'CamSnap', 'Capture frames or clips from RTSP/ONVIF cameras',
     '{"skills":{"entries":{"camsnap":{"enabled":true}}}}'::jsonb, 5),
    ('canvas', 'skill', 'Canvas', 'OpenClaw canvas skill',
     '{"skills":{"entries":{"canvas":{"enabled":true}}}}'::jsonb, 6),
    ('clawhub', 'skill', 'ClawHub', 'Search, install, update, and publish agent skills from clawhub.com',
     '{"skills":{"entries":{"clawhub":{"enabled":true}}}}'::jsonb, 7),
    ('coding-agent', 'skill', 'Coding Agent', 'Delegate coding tasks to Codex, Claude Code, or Pi agents',
     '{"skills":{"entries":{"coding-agent":{"enabled":true}}}}'::jsonb, 8),
    ('gemini', 'skill', 'Gemini', 'Gemini CLI for one-shot Q&A, summaries, and generation',
     '{"skills":{"entries":{"gemini":{"enabled":true}}}}'::jsonb, 9),
    ('gh-issues', 'skill', 'GitHub Issues', 'Fetch GitHub issues, spawn sub-agents to implement fixes and open PRs',
     '{"skills":{"entries":{"gh-issues":{"enabled":true}}}}'::jsonb, 10),
    ('github', 'skill', 'GitHub', 'GitHub operations via gh CLI: issues, PRs, CI runs, code review',
     '{"skills":{"entries":{"github":{"enabled":true}}}}'::jsonb, 11),
    ('gog', 'skill', 'Google Workspace', 'Google Workspace CLI for Gmail, Calendar, Drive, Contacts, Sheets, Docs',
     '{"skills":{"entries":{"gog":{"enabled":true}}}}'::jsonb, 12),
    ('healthcheck', 'skill', 'Healthcheck', 'Host security hardening and risk-tolerance configuration',
     '{"skills":{"entries":{"healthcheck":{"enabled":true}}}}'::jsonb, 13),
    ('himalaya', 'skill', 'Himalaya', 'CLI to manage emails via IMAP/SMTP',
     '{"skills":{"entries":{"himalaya":{"enabled":true}}}}'::jsonb, 14),
    ('mcporter', 'skill', 'MCPorter', 'List, configure, auth, and call MCP servers/tools directly',
     '{"skills":{"entries":{"mcporter":{"enabled":true}}}}'::jsonb, 15),
    ('model-usage', 'skill', 'Model Usage', 'Summarize per-model usage and costs from CodexBar CLI',
     '{"skills":{"entries":{"model-usage":{"enabled":true}}}}'::jsonb, 16),
    ('nano-banana-pro', 'skill', 'Nano Banana Pro', 'Generate or edit images via Gemini 3 Pro Image',
     '{"skills":{"entries":{"nano-banana-pro":{"enabled":true}}}}'::jsonb, 17),
    ('nano-pdf', 'skill', 'Nano PDF', 'Edit PDFs with natural-language instructions',
     '{"skills":{"entries":{"nano-pdf":{"enabled":true}}}}'::jsonb, 18),
    ('notion', 'skill', 'Notion', 'Notion API for creating and managing pages, databases, and blocks',
     '{"skills":{"entries":{"notion":{"enabled":true}}}}'::jsonb, 19),
    ('obsidian', 'skill', 'Obsidian', 'Work with Obsidian vaults and automate via obsidian-cli',
     '{"skills":{"entries":{"obsidian":{"enabled":true}}}}'::jsonb, 20),
    ('openai-image-gen', 'skill', 'OpenAI Image Gen', 'Batch-generate images via OpenAI Images API',
     '{"skills":{"entries":{"openai-image-gen":{"enabled":true}}}}'::jsonb, 21),
    ('openai-whisper', 'skill', 'OpenAI Whisper', 'Local speech-to-text with the Whisper CLI',
     '{"skills":{"entries":{"openai-whisper":{"enabled":true}}}}'::jsonb, 22),
    ('openai-whisper-api', 'skill', 'OpenAI Whisper API', 'Transcribe audio via OpenAI Audio Transcriptions API',
     '{"skills":{"entries":{"openai-whisper-api":{"enabled":true}}}}'::jsonb, 23),
    ('oracle', 'skill', 'Oracle', 'Best practices for using the oracle CLI',
     '{"skills":{"entries":{"oracle":{"enabled":true}}}}'::jsonb, 24),
    ('session-logs', 'skill', 'Session Logs', 'Search and analyze your own session logs using jq',
     '{"skills":{"entries":{"session-logs":{"enabled":true}}}}'::jsonb, 25),
    ('skill-creator', 'skill', 'Skill Creator', 'Create, edit, improve, or audit AgentSkills',
     '{"skills":{"entries":{"skill-creator":{"enabled":true}}}}'::jsonb, 26),
    ('slack', 'skill', 'Slack', 'Control Slack including reacting to messages and pinning items',
     '{"skills":{"entries":{"slack":{"enabled":true}}}}'::jsonb, 27),
    ('summarize', 'skill', 'Summarize', 'Summarize or extract text/transcripts from URLs, podcasts, and local files',
     '{"skills":{"entries":{"summarize":{"enabled":true}}}}'::jsonb, 28),
    ('things-mac', 'skill', 'Things', 'Manage Things 3 via the things CLI on macOS',
     '{"skills":{"entries":{"things-mac":{"enabled":true}}}}'::jsonb, 29),
    ('tmux', 'skill', 'Tmux', 'Remote-control tmux sessions for interactive CLIs',
     '{"skills":{"entries":{"tmux":{"enabled":true}}}}'::jsonb, 30),
    ('trello', 'skill', 'Trello', 'Manage Trello boards, lists, and cards via the Trello REST API',
     '{"skills":{"entries":{"trello":{"enabled":true}}}}'::jsonb, 31),
    ('video-frames', 'skill', 'Video Frames', 'Extract frames or short clips from videos using ffmpeg',
     '{"skills":{"entries":{"video-frames":{"enabled":true}}}}'::jsonb, 32),
    ('voice-call', 'skill', 'Voice Call', 'Start voice calls via the OpenClaw voice-call plugin',
     '{"skills":{"entries":{"voice-call":{"enabled":true}}}}'::jsonb, 33),
    ('weather', 'skill', 'Weather', 'Get current weather and forecasts via wttr.in or Open-Meteo',
     '{"skills":{"entries":{"weather":{"enabled":true}}}}'::jsonb, 34),
    ('xurl', 'skill', 'X (Twitter)', 'Make authenticated requests to the X API for tweets, DMs, media',
     '{"skills":{"entries":{"xurl":{"enabled":true}}}}'::jsonb, 35)
ON CONFLICT (id) DO NOTHING;
