#!/bin/sh

exec 2>&1
mkdir -p /var/log
exec chpst -u hermes -e /run/ocm-service-env/pty-server \
    /bin/sh -c 'set -a; [ -f /opt/data/.env ] && . /opt/data/.env; set +a; exec /usr/local/bin/ocmptyd >> /var/log/pty-server.log 2>&1'
